version: "3"
services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    volumes:
      - ./mongodb-data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_USER=testuser
      - MONGO_PASSWORD=testpassword
      - MONGO_DB_NAME=testdb
    command: mongod --auth

  express:
    image: pulchra13/netspeedtest:0.1
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - MONGO_URI=mongodb://testuser:testpassword@mongodb:27017/testdb
      - CLIENT_IP=http://192.168.1.101:5173

